### ISSUE TITLE
Question: Does this library support Non-homogeneous Poisson processes? 

### ISSUE THREAD

**Issue by lwhite1** [rossetti/JSL#1]
Does this library support Non-homogeneous Poisson processes? If not, do you know of one that does?

I want to simulate a production system with arrivals that vary over time, such as a hospital emergency room or restaurant.

Thank you.

**Comment by rossetti** [comment]
Many commercial simulation packages support non-homogeneous Poisson processes.  The JSL does support NHPP.  An example can be found [here](https://git.uark.edu/rossetti/JSL/blob/master/src/main/java/ex/queueing/NHPDriverLicenseBureauWithQ.java).  The java doc for the package can be found [here](https://rossetti.git-pages.uark.edu/JSL-Documentation/jsl/modeling/elements/variable/nhpp/package-summary.html).

**Comment by lwhite1** [comment]
Thanks very much.
